-------------------------------------
CREATE TABLE ACCOMPANY (
    CONTENTID NUMBER,
    PLANNO NUMBER,
    USERID VARCHAR2(50),
    TITLE VARCHAR2(200),
    content VARCHAR2(1000),
    PLANDATE VARCHAR2(20),
    PLANTOTALDATE VARCHAR2(20),
    WRITEDATE VARCHAR2(30) default to_char(sysdate,'yyyy.mm.dd hh24:mi'),
    NUMPERSON NUMBER,
    CURPERSON NUMBER DEFAULT '0',
    PRIMARY KEY(USERID, CONTENTID),
    CONSTRAINT PLAN_FK FOREIGN KEY(PLANNO,USERID) 
    REFERENCES PLANNER(PLANNO,USERID) ON DELETE CASCADE
    );

CREATE SEQUENCE CONTENTID
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;
--------------------=--------------------
CREATE TABLE GROUPACC (
    CONTENTID NUMBER,
    LEADER VARCHAR2(50),
    USERID VARCHAR2(50),
    PRIMARY KEY(CONTENTID,USERID),
    CONSTRAINT GROUP_FK FOREIGN KEY(LEADER, CONTENTID)
    REFERENCES ACCOMPANY(USERID, CONTENTID) ON DELETE CASCADE
);

