CREATE TABLE GROUPACC (
    bno NUMBER,
    LEADER VARCHAR2(50),
    USERID VARCHAR2(50),
    PRIMARY KEY(bno,USERID),
    CONSTRAINT GROUP_FK FOREIGN KEY(leader, bno)
    REFERENCES ACCOMPANY(USERID, bno) ON DELETE CASCADE
);

drop table groupacc;