CREATE TABLE ACC_GUEST (
    GUESTID VARCHAR2(30),
    HOSTID VARCHAR2(30),
    PLANNO NUMBER,
    TITLE VARCHAR2(200),
    PRIMARY KEY(GUESTID,HOSTID,PLANNO,TITLE),
    CONSTRAINT GUEST_FK_ACC_HOST FOREIGN KEY(PLANNO, HOSTID, TITLE)
    REFERENCES ACC_HOST(PLANNO, HOSTID, TITLE) ON DELETE CASCADE
);

drop table acc_GUEst;