DROP TABLE ACC_HOST;
CREATE TABLE ACC_HOST (
    PLANNO NUMBER, 
    HOSTID VARCHAR2(30),
    TITLE VARCHAR2(200),
    LIMIT_PERSON NUMBER,
    CUR_PERSON NUMBER,
    ACC_DESCRIPT VARCHAR2(4000),
    PRIMARY KEY(PLANNO,HOSTID,TITLE),
    CONSTRAINT HOST_FK_USERPLAN FOREIGN KEY(PLANNO, HOSTID, TITLE)
    REFERENCES USERPLAN(PLANNO, USERID, TITLE) ON DELETE CASCADE
);