DROP TABLE USERPLAN;

CREATE TABLE USERPLAN (
    PLANNO NUMBER,
    USERID VARCHAR2(50),
    TITLE VARCHAR2(200),
    CONTENTID VARCHAR2(10),
    CONTENTTYPEID VARCHAR2(5),
    ADDR VARCHAR2(200),
    IMG_SRC VARCHAR2(300),
    MAPX VARCHAR2(20),
    MAPY VARCHAR2(20),
    PLANDATE VARCHAR2(20),
    PLANDAY VARCHAR2(30),
    PLANTOTALDATE VARCHAR2(30),
    STARTDATE VARCHAR2(20),
    ENDDATE VARCHAR2(20),
    DESCRIPT VARCHAR2(1000),
    IS_INSERTAFTER VARCHAR(1) DEFAULT 'N',
    PRIMARY KEY(PLANNO,USERID, TITLE),
    CONSTRAINT PLANNER_FK_ID_PLANNO FOREIGN KEY(PLANNO,USERID) 
    REFERENCES PLANNER(PLANNO,USERID) ON DELETE CASCADE
    );
